# Generated by Django 4.1 on 2023-01-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyAsset',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'db_table': 'currency_asset',
            },
        ),
        migrations.CreateModel(
            name='QuotesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('quote', models.FloatField()),
                ('currency_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.currencyasset')),
            ],
            options={
                'db_table': 'quotes_history',
                'unique_together': {('time', 'currency_asset')},
            },
        ),
        migrations.RunSQL(
            """
            INSERT INTO currency_asset (id, name)
            VALUES
            (1, "EURUSD"),
            (2, "USDJPY"),
            (3, "GBPUSD"),
            (4, "AUDUSD"),
            (5, "USDCAD");

            """,
            """
            """
        )
    ]
